#!/usr/bin/env bash
set -euo pipefail

# -------- CONFIG --------
NAV_CONFIG="client/src/config/music-nav-links.ts"
NAV_COMPONENT="client/src/components/music-app-nav.tsx"
SHELL_COMPONENT="client/src/components/music-page-shell.tsx"

NAV_BLOCK=$(cat <<'EOF'
      <Link href="/daw"        className="ag-nav-btn">🎚 Studio</Link>
      <Link href="/collab"     className="ag-nav-btn">⬡ Collab</Link>
      <Link href="/multitrack" className="ag-nav-btn">📼 Multitrack</Link>
      <Link href="/mixer"      className="ag-nav-btn">⟳ Mixer</Link>
      <Link href="/instrument" className="ag-nav-btn">🎹 Instrument</Link>
EOF
)

# ---------- 1. SAFELY CREATE CONSTANT CONFIG ----------
if [[ -e "$NAV_CONFIG" ]]; then
  echo "SKIP: $NAV_CONFIG already exists."
else
  mkdir -p "$(dirname "$NAV_CONFIG")"
  cat > "$NAV_CONFIG" <<EOF
// Auto-generated by gold-dry-music-nav.sh
export const MUSIC_NAV_LINKS = [
  { href: "/daw",        label: "🎚 Studio" },
  { href: "/collab",     label: "⬡ Collab" },
  { href: "/multitrack", label: "📼 Multitrack" },
  { href: "/mixer",      label: "⟳ Mixer" },
  { href: "/instrument", label: "🎹 Instrument" },
] as const;
EOF
  echo "WROTE: $NAV_CONFIG"
fi

# ---------- 2. SAFELY CREATE NAV COMPONENT ----------
if [[ -e "$NAV_COMPONENT" ]]; then
  echo "SKIP: $NAV_COMPONENT already exists."
else
  mkdir -p "$(dirname "$NAV_COMPONENT")"
  cat > "$NAV_COMPONENT" <<'EOF'
import Link from "next/link";
import { useRouter } from "next/router";
import { MUSIC_NAV_LINKS } from "@/config/music-nav-links";

export function MusicAppNav() {
  const { pathname } = useRouter();
  return (
    <nav className="ag-controls-block">
      {MUSIC_NAV_LINKS.map(({ href, label }) => (
        <Link
          href={href}
          key={href}
          className={
            "ag-nav-btn" +
            (pathname.startsWith(href) ? " ag-nav-active" : "")
          }
        >
          {label}
        </Link>
      ))}
    </nav>
  );
}
EOF
  echo "WROTE: $NAV_COMPONENT"
fi

# ---------- 3. SAFELY CREATE SHELL COMPONENT ----------
if [[ -e "$SHELL_COMPONENT" ]]; then
  echo "SKIP: $SHELL_COMPONENT already exists."
else
  mkdir -p "$(dirname "$SHELL_COMPONENT")"
  cat > "$SHELL_COMPONENT" <<'EOF'
import { MusicAppNav } from "@/components/music-app-nav";

export function MusicPageShell({ header, transportBar, children }) {
  return (
    <>
      <header className="ag-header">
        {header}
        <MusicAppNav />
      </header>
      {transportBar}
      <main className="ag-frame ag-content">
        {children}
      </main>
    </>
  );
}
EOF
  echo "WROTE: $SHELL_COMPONENT"
fi

# ---------- 4. PATCH EXISTING PAGES WITH DRY NAV ----------
echo "== Scanning music pages for DRY navification =="

patched_files=()
for page in client/src/pages/*.tsx; do
  block=$(awk '/<div className="ag-controls-block">/{f=1} f{print} /<\/div>/{if(f){exit}}' "$page" | sed '1d;$d' | sed 's/^[ \t]*//')
  [[ -z "$block" ]] && continue
  block_canonical=$(echo "$block" | tr -d '\n' | tr -s ' ')
  nav_canonical=$(echo "$NAV_BLOCK" | tr -d '\n' | tr -s ' ')
  if [[ "$block_canonical" == "$nav_canonical" ]]; then
    # --- PATCH: replace old nav with <MusicAppNav /> ---
    cp "$page" "$page.bak"
    awk '
      /<div className="ag-controls-block">/ {f=1; print "      <MusicAppNav />"; next}
      f && /<\/div>/ {f=0; next}
      !f {print}
    ' "$page.bak" > "$page.tmp"
    # idempotently add import if missing
    if ! grep -q "import { MusicAppNav }" "$page.tmp"; then
      awk 'NR==1{print "import { MusicAppNav } from \"@/components/music-app-nav\";"} 1' "$page.tmp" > "$page"
      rm "$page.tmp"
    else
      mv "$page.tmp" "$page"
    fi
    patched_files+=("$page")
    echo "PATCHED: $page (backup: $page.bak)"
    echo "      To migrate to PageShell, refactor page body as described in docs/onboarding, passing custom header/transportBar if needed."
  fi
done

if [[ ${#patched_files[@]} -eq 0 ]]; then
  echo "No legacy nav blocks found in pages. DRY nav is already in effect."
fi

# ---------- 5. SUMMARY AND NEXT STEPS ----------
echo "================ SUMMARY ================"
[[ ${#patched_files[@]} -gt 0 ]] && echo "Patched:" "${patched_files[@]}"
echo "---------------------"
echo "Created or preserved:"
echo "  $NAV_CONFIG"
echo "  $NAV_COMPONENT"
echo "  $SHELL_COMPONENT"
echo ""
echo "REMINDER: For full DRYness and layout hygiene, incrementally migrate relevant pages to:"
echo ""
cat <<EX
import { MusicPageShell } from "@/components/music-page-shell";
//...
<MusicPageShell header={<YourHeaderStuff />} transportBar={<TransportControls />}>
  {/* page content here */}
</MusicPageShell>
EX
echo ""
echo "After any changes, run: pnpm tsc --noEmit && npm run lint"
echo "========== ALL DONE =========="

exit 0
