#!/usr/bin/env python3
"""Auto-generated by audit_theme_config.py — do not edit manually."""
import re, sys
from pathlib import Path

DRY_RUN = "--apply" not in sys.argv
TARGET = Path.home() / "Stable/client/src/lib/theme-config.ts"

HEX_MAP = {
    "#020617": "var(--panel-deep)",
    "#10b981": "var(--status-ok)",
    "#8b95a1": "var(--text-dim)",
    "#c5c9cc": "var(--text-secondary)",
    "#f59e0b": "var(--status-warn)",
}

HEX_RE = re.compile(r'(?<![0-9a-fA-F])(#[0-9a-fA-F]{3,6})(?![0-9a-fA-F])', re.IGNORECASE)

def replace(line):
    def sub(m):
        return HEX_MAP.get(m.group(1).lower(), m.group(1))
    return HEX_RE.sub(sub, line)

src = TARGET.read_text(encoding="utf-8")
lines = src.splitlines(keepends=True)
new_lines = [replace(l) for l in lines]
changed = [(i+1, o, n) for i, (o, n) in enumerate(zip(lines, new_lines)) if o != n]

print(f"  theme_config_patch — {'DRY RUN' if DRY_RUN else 'APPLYING'} — {len(changed)} lines")
for lineno, old, new in changed:
    print(f"  L{lineno:>4} - {old.rstrip()}")
    print(f"       + {new.rstrip()}")

if not DRY_RUN:
    TARGET.write_text("".join(new_lines), encoding="utf-8")
    print("  [WRITTEN]")
else:
    print("  Re-run with --apply to write.")
