// @ts-nocheck
// NOTE: This file is auto-generated by refactor script.
// Replace with architecture version from LoopStation refactor doc if needed.

import { useReducer, useCallback } from 'react';
import { getLoopEngine } from '../engine/loopEngine';
import { reducer } from '../state/reducer';
import { initialState } from '../state/initialState';
import { transitionTrack } from '../state/machine';

export function useLoopStation() {
  const [state, dispatch] = useReducer(reducer, initialState);
  const engine = getLoopEngine();

  const pressTrack = useCallback((trackId: string) => {
    const track = state.tracks.find(t => t.id === trackId);
    if (!track) return;

    const updated = transitionTrack(track, engine);

    dispatch({
      type: 'SET_TRACKS',
      tracks: state.tracks.map(t =>
        t.id === trackId ? updated : t
      ),
    });
  }, [state.tracks]);

  const togglePlayback = useCallback(() => {
    engine.toggleTransport();
    dispatch({ type: 'TOGGLE_PLAY' });
  }, []);

  const setBpm = useCallback((bpm: number) => {
    engine.setBpm(bpm);
    dispatch({ type: 'SET_BPM', bpm });
  }, []);

  return {
    state,
    pressTrack,
    togglePlayback,
    setBpm,
  };
}
