import type { ChannelState } from "./types";

export const _defaultChannel = (id: number, color = "#06b6d4"): ChannelState => ({
  id,
  name: `Ch ${id}`,
  color,
  inputType: "xlr",
  gain: 12,
  phantom: false,
  phase: false,
  lowCut: false,
  eqLow: 0,
  eqLowMid: 0,
  eqHighMid: 0,
  eqHigh: 0,
  eqLowFreq: 80,
  eqHighFreq: 8,
  compression: 2,
  compThreshold: -12,
  compAttack: 10,
  compRelease: 200,
  compKnee: 1,
  noiseGate: false,
  gateThreshold: -40,
  gateAttack: 10,
  gateRelease: 100,
  deEsser: false,
  deEsserFreq: 6,
  limiter: false,
  limiterThreshold: -6,
  pan: 0,
  fader: 80,
  mute: false,
  solo: false,
  reverb: 0,
  delay: 0,
  delayTime: 300,
  chorus: 0,
  auxSend1: 0,
  auxSend2: 0,
  level: 0,
  peakLevel: 0,
  recording: false,
});
